//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesToDataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Authors
    {
        public Authors()
        {
            this.Base = new HashSet<Base>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public int Year { get; set; }
    
        public virtual ICollection<Base> Base { get; set; }
    }
}
