//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesToDataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Base
    {
        public Base()
        {
            this.ContestToQuestion = new HashSet<ContestToQuestion>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string Answear { get; set; }
        public int Year { get; set; }
        public string Comment { get; set; }
        public int AuthorID { get; set; }
        public int TypeID { get; set; }
        public int DifficultyID { get; set; }
    
        public virtual Authors Authors { get; set; }
        public virtual Difficulties Difficulties { get; set; }
        public virtual TypeOfQuestion TypeOfQuestion { get; set; }
        public virtual ICollection<ContestToQuestion> ContestToQuestion { get; set; }
    }
}
