//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesToDataBase
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class IntelectualGamesImprovedEntities : DbContext
    {
        public IntelectualGamesImprovedEntities()
            : base("name=IntelectualGamesImprovedEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Authors> Authors { get; set; }
        public virtual DbSet<Base> Base { get; set; }
        public virtual DbSet<Contests> Contests { get; set; }
        public virtual DbSet<ContestToQuestion> ContestToQuestion { get; set; }
        public virtual DbSet<ContestToTeam> ContestToTeam { get; set; }
        public virtual DbSet<Difficulties> Difficulties { get; set; }
        public virtual DbSet<Players> Players { get; set; }
        public virtual DbSet<PlayerToTeam> PlayerToTeam { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Teams> Teams { get; set; }
        public virtual DbSet<TypeOfQuestion> TypeOfQuestion { get; set; }
    }
}
