//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesToDataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Teams
    {
        public Teams()
        {
            this.ContestToTeam = new HashSet<ContestToTeam>();
            this.PlayerToTeam = new HashSet<PlayerToTeam>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public int Year { get; set; }
    
        public virtual ICollection<ContestToTeam> ContestToTeam { get; set; }
        public virtual ICollection<PlayerToTeam> PlayerToTeam { get; set; }
    }
}
